sar.py fails with AttributeError: 'User' object has no attribute 'social_auth'