No error was shown when check_service thread crashed
